// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zehsqqpveoptiiubpqpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplaHNxcXB2ZW9wdGlpdWJwcXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzkxMjksImV4cCI6MjA2MDMxNTEyOX0.BSPRLcH_4gU3FrGFhB0lZV_YuzulY5rWkXc0pgQjB5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);